### ISSUE TITLE
小红书短链解析失败

### ISSUE THREAD

**Issue by YipSzeho** [fllesser/nonebot-plugin-parser#2]
发送文本形如
`45 波妞有家了发布了一篇小红书笔记，快来看吧！ 😆 C4QcUbe3ImNZyv3 😆 http://xhslink.com/a/zGL52ubtpJ20，复制本条信息，打开【小红书】App查看精彩内容！`

后台log
```
12-05 12:08:02 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_resolver2.matchers.xiaohongshu, lineno=18) failed.
Traceback (most recent call last):
  File "/root/nb/bot.py", line 17, in <module>
    nonebot.run()
  File "/root/nb/.venv/lib/python3.12/site-packages/nonebot/__init__.py", line 337, in run
    get_driver().run(*args, **kwargs)
  File "/root/nb/.venv/lib/python3.12/site-packages/nonebot/drivers/fastapi.py", line 188, in run
    uvicorn.run(
  File "/root/nb/.venv/lib/python3.12/site-packages/uvicorn/main.py", line 579, in run
    server.run()
  File "/root/nb/.venv/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/root/nb/.venv/lib/python3.12/site-packages/nonebot/utils.py", line 254, in run_coro_with_shield
    return await coro
  File "/root/nb/.venv/lib/python3.12/site-packages/nonebot/message.py", line 506, in check_and_run_matcher
    await _run_matcher(
> File "/root/nb/.venv/lib/python3.12/site-packages/nonebot/message.py", line 458, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/nb/.venv/lib/python3.12/site-packages/nonebot/internal/matcher/matcher.py", line 900, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/nb/.venv/lib/python3.12/site-packages/nonebot/internal/matcher/matcher.py", line 837, in simple_run
    await handler(
  File "/root/nb/.venv/lib/python3.12/site-packages/nonebot/dependencies/__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/nb/.venv/lib/python3.12/site-packages/nonebot_plugin_resolver2/matchers/xiaohongshu.py", line 37, in _
    if match := re.search(pattern, msg_url):
  File "/usr/lib/python3.12/re/__init__.py", line 177, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object, got 'URL'
```

**Comment by fllesser** [comment]
收到，忘记把 resp.url 转字符串了，下个版本修

**Comment by fllesser** [comment]
已在 `1.4.1` 修复（就一行用手机改的，忘记引用issue了 `9d9efe9`）

**Comment by fllesser** [comment]
![1733374943581_edit_95531888834900.jpg](https://github.com/user-attachments/assets/ca11f1b4-fcf1-402e-b953-4cbc066adbe4)

咪咪不错

**Comment by YipSzeho** [comment]
OK了，多谢大佬（吸猫
