### ISSUE TITLE
下载X图片失败

### ISSUE THREAD

**Issue by ttlvip** [fllesser/nonebot-plugin-parser#7]
12-21 15:11:37 [SUCCESS] nonebot | OneBot V11 649565448 | [message.group.normal]: Message 1657399951 from 164xxxx448@[群:243xxxx69] 'https://x.com/yama149983/status/1869748430689706354?s=46'
12-21 15:11:37 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.third_plugins.nonebot_plugin_resolver2.matchers.twitter, lineno=15)
12-21 15:11:37 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39)
12-21 15:11:37 [INFO] nonebot | Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39) running complete
12-21 15:11:48 [WARNING] nonebot_plugin_resolver2 | download_img err:
12-21 15:11:52 [INFO] nonebot | Matcher(type='message', module=zhenxun.third_plugins.nonebot_plugin_resolver2.matchers.twitter, lineno=15) running complete
12-21 15:11:52 [ERROR] nonebot | Running Matcher(type='message', module=zhenxun.third_plugins.nonebot_plugin_resolver2.matchers.twitter, lineno=15) failed.
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\PyCharm Professional\plugins\python-ce\helpers\pydev\pydevd.py", line 2270, in <module>
    main()
  File "C:\Users\Administrator\AppData\Local\Programs\PyCharm Professional\plugins\python-ce\helpers\pydev\pydevd.py", line 2252, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Users\Administrator\AppData\Local\Programs\PyCharm Professional\plugins\python-ce\helpers\pydev\pydevd.py", line 1563, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "C:\Users\Administrator\AppData\Local\Programs\PyCharm Professional\plugins\python-ce\helpers\pydev\pydevd.py", line 1570, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\Administrator\AppData\Local\Programs\PyCharm Professional\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\workspace\zhenxun\zhenxun_bot\bot.py", line 33, in <module>
    nonebot.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EqGhmUXJ-py3.11\Lib\site-packages\nonebot\__init__.py", line 337, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EqGhmUXJ-py3.11\Lib\site-packages\nonebot\drivers\fastapi.py", line 188, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EqGhmUXJ-py3.11\Lib\site-packages\uvicorn\main.py", line 579, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EqGhmUXJ-py3.11\Lib\site-packages\uvicorn\server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\PyCharm Professional\plugins\python\helpers-pro\pydevd_asyncio\pydevd_nest_asyncio.py", line 138, in run
    return loop.run_until_complete(task)
  File "C:\Users\Administrator\AppData\Local\Programs\PyCharm Professional\plugins\python\helpers-pro\pydevd_asyncio\pydevd_nest_asyncio.py", line 234, in run_until_complete
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\PyCharm Professional\plugins\python\helpers-pro\pydevd_asyncio\pydevd_nest_asyncio.py", line 286, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\Programs\PyCharm Professional\plugins\python\helpers-pro\pydevd_asyncio\pydevd_nest_asyncio.py", line 394, in step
    step_orig(task, exc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 277, in __step
    result = coro.send(None)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EqGhmUXJ-py3.11\Lib\site-packages\nonebot\utils.py", line 254, in run_coro_with_shield
    return await coro
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EqGhmUXJ-py3.11\Lib\site-packages\nonebot\message.py", line 506, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EqGhmUXJ-py3.11\Lib\site-packages\nonebot\message.py", line 458, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EqGhmUXJ-py3.11\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 900, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EqGhmUXJ-py3.11\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 837, in simple_run
    await handler(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EqGhmUXJ-py3.11\Lib\site-packages\nonebot\dependencies\__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\workspace\zhenxun\zhenxun_bot\zhenxun\third_plugins\nonebot_plugin_resolver2\matchers\twitter.py", line 55, in _
    await twitter.send(MessageSegment.image(plugin_cache_dir / img_name))
TypeError: unsupported operand type(s) for /: 'WindowsPath' and 'NoneType'

**Comment by ttlvip** [comment]
经过排查发现twitter.py第54行返回的img_name为None，导致第55行报错

**Comment by fllesser** [comment]
![1734779923412_edit_98571602827666.jpg](https://github.com/user-attachments/assets/fbe509e2-183b-467a-8cda-83820874b459)

未复现，可能是你代理的问题

**Comment by ttlvip** [comment]
经过测试，添加https代理可能有效。
`    # 配置代理
    if proxy:
        client_config['proxies'] = {
            'http://': proxy,
            'https://': proxy
        }
`
